title: Strategic Academic Plan
email: academicplan@ucsc.edu
description: "UC Santa Cruz has the capacity to take a greater role on the international stage: to lead with our cutting-edge scholarship, to offer new strategies for engaged and ethical pedagogy, and to provide a visionary model for public higher education - qualities that honor and advance our founding mission. We can."
url: "https://sap.ucsc.edu"
timezone: "America/Los_Angeles"

# Build settings
markdown: kramdown
permalink: /:year/:month/:title/

plugins:
  - jekyll-feed
  - jekyll-seo-tag

collections_dir: collections
collections:
  announcements:
    label: "announcements"
    output: true
  links:
    label: "links"
    output: false
  posts:
    label: "posts"
    output: true

defaults:
  - scope:
      path: ""
    values:
      image: /assets/images/cl-web.jpg
assets:
  sources:
    - assets/images
    - assets/css
    - assets/pdfs

include:
  - _redirects

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - sap-jekyll-export
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
