# A redirect rule with all the supported properties
[[redirects]]
  from = "/design-principles/"
  to = "/guiding-principles/"
  status = 301
  force = true

[[redirects]]
  from = "/news/"
  to = "/"
  status = 301
  force = true

[[redirects]]
  from = "/2017/*"
  to = "/"
  status = 301
  force = true
[[redirects]]
  from = "/2018/*"
  to = "/"
  status = 301
  force = true
[[redirects]]
  from = "/2019/*"
  to = "/"
  status = 301
  force = true
[[redirects]]
  from = "/2020/*"
  to = "/"
  status = 301
  force = true
[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "default-src 'self' 'unsafe-inline' *.ucsc.edu; img-src 'self' *.ucsc.edu *.rackcdn.com data:; script-src 'self' 'unsafe-inline' unpkg.com *.netlify.com www.google-analytics.com ajax.googleapis.com *.googletagmanager.com use.fontawesome.com *.google.com *.ucsc.edu;  style-src data: 'self' 'unsafe-inline' fonts.googleapis.com fonts.gstatic.com unpkg.com *.fontawesome.com *.ucsc.edu; frame-src 'self' *.youtube.com; object-src 'none'; font-src 'self' fonts.gstatic.com;"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    X-Frame-Options = "DENY"
