# A redirect rule with all the supported properties
[[redirects]]
  from = "/news/"
  to = "/"
  status = 301
  force = true

[[redirects]]
  from = "/2017/*"
  to = "/"
  status = 301
  force = true
[[redirects]]
  from = "/2018/*"
  to = "/"
  status = 301
  force = true
[[redirects]]
  from = "/2019/*"
  to = "/"
  status = 301
  force = true
[[redirects]]
  from = "/2020/*"
  to = "/"
  status = 301
  force = true

# headers
[[headers]]
  for = "/*"
  [headers.values]
    # Content-Security-Policy = "default-src 'self';"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
